# Save and restore variables

In [1]:
import tensorflow as tf

from tensorflow.python.tools import inspect_checkpoint as chkp

## Example 1

In [2]:
tf.reset_default_graph()

v1 = tf.get_variable('v1', shape=[5], initializer=tf.ones_initializer())
v2 = tf.get_variable('v2', shape=[5], initializer=tf.ones_initializer())
v3 = v1 + v2

init = tf.global_variables_initializer()
saver = tf.train.Saver({'v1': v1})

with tf.Session() as sess:
    init.run()
    saver.save(sess, './checkpoints/model_1.ckpt')

chkp.print_tensors_in_checkpoint_file('./checkpoints/model_1.ckpt', tensor_name='', all_tensors=True)

tensor_name:  v1
[1. 1. 1. 1. 1.]


## Example 2

In [3]:
tf.reset_default_graph()

v1 = tf.get_variable('v1', shape=[5], initializer=tf.ones_initializer())
v2 = tf.get_variable('v2', shape=[5], initializer=tf.ones_initializer())
v3 = v1 + v2

init = tf.global_variables_initializer()
saver = tf.train.Saver()

with tf.Session() as sess:
    init.run()
    saver.save(sess, './checkpoints/model_2.ckpt')

chkp.print_tensors_in_checkpoint_file('./checkpoints/model_2.ckpt', tensor_name='', all_tensors=True)

tensor_name:  v1
[1. 1. 1. 1. 1.]
tensor_name:  v2
[1. 1. 1. 1. 1.]


## Example 3

In [4]:
tf.reset_default_graph()

v1 = tf.get_variable('v1', shape=[5])
v2 = tf.get_variable('v2', shape=[5])
v3 = v1 + v2

saver = tf.train.Saver()
with tf.Session() as sess:
    saver.restore(sess, './checkpoints/model_2.ckpt')
    chkp.print_tensors_in_checkpoint_file('./checkpoints/model_2.ckpt', tensor_name='', all_tensors=True)
    print()
    print(v1.eval())
    print(v2.eval())
    print(v3.eval())

INFO:tensorflow:Restoring parameters from ./checkpoints/model_2.ckpt
tensor_name:  v1
[1. 1. 1. 1. 1.]
tensor_name:  v2
[1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
