In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.Variable([[7],[8],[9],[5]], dtype=tf.float32)
b = tf.Variable([[6],[10],[13],[5]], dtype=tf.float32)

delta = 1
huber_loss = tf.losses.huber_loss(labels=a,
                                  predictions=b)

In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    a_np = a.eval()
    b_np = b.eval()
    huber_loss_np = huber_loss.eval()

    diff = a_np - b_np
    huber_loss_precomp = np.zeros_like(a_np).squeeze()
    for i in range(len(huber_loss_precomp)):
        if abs(diff[i]) <= delta:
            huber_loss_precomp[i] = 0.5 * (diff.squeeze()[i] ** 2)
        else:
            huber_loss_precomp[i] = delta * (abs(diff.squeeze()[i]) - 0.5 * delta)

print(f'a:\n{a_np}, {a_np.shape}\n')
print(f'b:\n{b_np}, {b_np.shape}\n')
print(f'diff:\n{diff}\n')
print(f'huber_loss_precomputed:')
print(huber_loss_precomp)
print('sum: ', huber_loss_precomp.sum())
print('mean: ', huber_loss_precomp.mean())
print(f'\nhuber_loss (tensorflow):', huber_loss_np)

a:
[[7.]
 [8.]
 [9.]
 [5.]], (4, 1)

b:
[[ 6.]
 [10.]
 [13.]
 [ 5.]], (4, 1)

diff:
[[ 1.]
 [-2.]
 [-4.]
 [ 0.]]

huber_loss_precomputed:
[0.5 1.5 3.5 0. ]
sum:  5.5
mean:  1.375

huber_loss (tensorflow): 1.375
