# Constants

In [1]:
import tensorflow as tf

## Create a constant

In [2]:
c = tf.constant(5, name='my_constant')

with tf.Session() as sess:
    print(c)
    print(sess.run(c))

Tensor("my_constant:0", shape=(), dtype=int32)
5


In [3]:
c = tf.zeros([3, 7])

with tf.Session() as sess:
    print(c)
    print(sess.run(c))

Tensor("zeros:0", shape=(3, 7), dtype=float32)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Add 2 constants

In [4]:
a = tf.constant([3, 5])
b = tf.constant([7, 9])
c = tf.add(a, b, name='add_operation')

with tf.Session() as sess:
    print(c)
    print(sess.run(c))

Tensor("add_operation:0", shape=(2,), dtype=int32)
[10 14]


## Argmax of a constant tensor

In [5]:
c = tf.constant([4, 5, 2, 9, 8, -1])
argmax_op = tf.argmax(c)

with tf.Session() as sess:
    print(c)
    print(argmax_op)
    print(sess.run(argmax_op))

Tensor("Const_2:0", shape=(6,), dtype=int32)
Tensor("ArgMax:0", shape=(), dtype=int64)
3
