# Variables

In [1]:
import tensorflow as tf

## Create a variable

In [2]:
a = tf.Variable(5, name='my_variable')

with tf.Session() as sess:
    print(a)
    sess.run(a.initializer) # initialize a
    print(sess.run(a))

<tf.Variable 'my_variable:0' shape=() dtype=int32_ref>
5


In [3]:
b = tf.Variable([7], name='my_variable_2')

with tf.Session() as sess:
    print(b)
    sess.run(tf.global_variables_initializer())
    print(sess.run(b))

<tf.Variable 'my_variable_2:0' shape=(1,) dtype=int32_ref>
[7]


In [4]:
c = tf.get_variable('my_variable_3', shape=[], initializer=tf.ones_initializer())

with tf.Session() as sess:
    print(c)
    sess.run(tf.global_variables_initializer())
    print(sess.run(c))

<tf.Variable 'my_variable_3:0' shape=() dtype=float32_ref>
1.0


## Variable scope

In [5]:
with tf.variable_scope('conv_layer_1'):
    w = tf.get_variable('weights', shape=[2,4,3,3])
    b = tf.get_variable('bias', shape=[4])
    
print(w)
print(b)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    w_np, b_np = sess.run([w, b])
    print(w_np)
    print(b_np)

<tf.Variable 'conv_layer_1/weights:0' shape=(2, 4, 3, 3) dtype=float32_ref>
<tf.Variable 'conv_layer_1/bias:0' shape=(4,) dtype=float32_ref>
[[[[ 0.02130371  0.2490749   0.30134627]
   [ 0.187763   -0.30569994  0.01177144]
   [-0.1806488   0.08117053  0.23469332]]

  [[-0.09701008 -0.03358439 -0.30748695]
   [ 0.19862804 -0.35282037  0.09220752]
   [-0.01007932  0.2719145  -0.13614334]]

  [[-0.19901454 -0.20966008 -0.17197178]
   [ 0.06422043  0.28481373 -0.3445423 ]
   [ 0.1931208  -0.01269352 -0.1606648 ]]

  [[-0.3455357  -0.13788013  0.30084363]
   [ 0.15995243  0.30784127  0.02130389]
   [ 0.06994134 -0.2021706   0.13258445]]]


 [[[-0.04384562 -0.16384529 -0.1007925 ]
   [-0.35341886 -0.26121065 -0.16902909]
   [ 0.3520479   0.04700041 -0.07067007]]

  [[-0.17795074  0.28255227 -0.06895569]
   [ 0.16296443  0.35001162  0.02668756]
   [-0.12336121 -0.28974533 -0.26799065]]

  [[ 0.10305816  0.30050233  0.22289923]
   [-0.03606471 -0.30439803 -0.28686586]
   [-0.00522384  0.292159

In [6]:
with tf.variable_scope('test'):
    x = tf.Variable(5)

print(x)
with tf.Session() as sess:
    print(sess.run(x, feed_dict={x: 12345}))

<tf.Variable 'test/Variable:0' shape=() dtype=int32_ref>
12345
